# http://cluex-developers.hateblo.jp/entry/2019/01/10/171237
extends:
  - standard
  - plugin:react/recommended
plugins:
  - react
rules:
  react/prop-types:
    - 0
  prettier/prettier:
    - error
settings:
  react:
    version: 16.9 # Reactのバージョン