# http://cluex-developers.hateblo.jp/entry/2019/01/10/171237
extends:
  - standard
  - plugin:react/recommended
  - prettier
plugins:
  - react
rules:
  space-before-function-paren:
    - 0
  react/prop-types:
    - 0
settings:
  react:
    version: 16.9 # Reactのバージョン